import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ApiProvider from "@/commons/providers/13-04-api-provider";
import Layout from "@/commons/layout";
import ApiUploadProvider from "@/commons/providers/18-01-api-upload-provider";
import ApiHeaderProvider from "@/commons/providers/20-03-api-header-provider";
import ApiRefreshtokenProvider from "@/commons/providers/30-01-api-refreshtoken-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ApiProvider>
          <Layout>{children}</Layout>
        </ApiProvider> */}

        {/* 18-01 이미지업로드 */}
        {/* <ApiUploadProvider>
          <Layout>{children}</Layout>
        </ApiUploadProvider> */}

        {/* 20-01 로그인토큰 */}
        {/* <ApiHeaderProvider>
          <Layout>{children}</Layout>
        </ApiHeaderProvider> */}

        {/* 20-03 로그인토큰 - 로컬스토리지 */}
        {/* <ApiHeaderProvider>
          <Layout>{children}</Layout>
        </ApiHeaderProvider> */}

        {/* 30-01 리프레시토큰 */}
        <ApiRefreshtokenProvider>
          <Layout>{children}</Layout>
        </ApiRefreshtokenProvider>
      </body>
    </html>
  );
}
